FROM python:3.11

EXPOSE  8080
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6

RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python3", "api.py"]
